server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/ncre?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8mb4
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # session配置
  session:
    timeout: 604800 # 设置session失效时间
    store-type: redis # 修改spring-session存储配置，默认存储到服务器内存中，现在设置存到redis中（关键）
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: 123456
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.ncre_system_idea.pojo